// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.ConnConfig):Promise<string>;

export function DownloadFile(arg1:string,arg2:string):Promise<string>;

export function ListDir(arg1:string):Promise<Array<string>>;

export function Mkdir(arg1:string):Promise<string>;

export function RemoveFile(arg1:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SendCmd(arg1:string):Promise<string>;

export function UploadFileBin(arg1:string,arg2:Array<number>):Promise<string>;
